shellEmulator: true
publicHoistPattern:
  - '*types*'
  - '@eslint/*'
  - '@astrojs/*'
  - katex
  - react
  - decap-cms-app
  - decap-cms-core
packageExtensions:
  decap-cms-widget-markdown:
    peerDependencies:
      slate-hyperscript: '*'
