packageExtensions:
  decap-cms-widget-markdown:
    peerDependencies:
      slate-hyperscript: '*'
publicHoistPattern:
  - '*types*'
  - '*eslint*'
  - katex
  - react
  - decap-cms-app
  - decap-cms-core
shellEmulator: true
